### ISSUE TITLE
linuxemu_EnterCritical and linuxemu_LeaveCritical need to be visible for sample environment to work

### ISSUE THREAD

**Issue by prakol16** [kawa-yoiko/AMPi#1]
The naive, default version of `ampi_malloc` is defined as:

```
void *ampi_malloc (size_t size)
{
	linuxemu_EnterCritical();
	void *ret = (void *)(pool + ptr);
	ptr += size;
	linuxemu_LeaveCritical();
	return ret;
}
```

Unfortunately, `linuxemu_EnterCritical` and `linuxemu_LeaveCritical` are not publicly exposed, which means there is a linking error. There should be an `__attribute__((visibility("default")))` by their definitions in `ampi/linux/synchronize.c`.

**Comment by ayuusweetfish** [comment]
Thanks for pointing out the mistake!

`linuxemu_LeaveCritical` is not intended to be exposed, and instead a simpler implementation is added to the sample environment in commit 6256e52. Please confirm whether it works.

**Comment by prakol16** [comment]
Yes, this worked on my Raspberry Pi.

**Comment by ayuusweetfish** [comment]
Great! Closing then.
